### ISSUE TITLE
error when selecting the country for the investigation

### ISSUE THREAD

**Issue by ManuelQ59** [Nwqda/BiG-Brother#2]
I have run the tool, after entering and validating the shodan key, it asks me to enter the country for the investigation and it throws me the following error:

🏳] In which country do you want to focus your research?  PE
[/] The research of cameras has begun. It may take a while, please be patient.

[🚫] Error: Retry limit reached (5). Please, try again.
[😓] No result found. Please try again using another keywords or dorks combo.

[👹] See you soon for a new adventure!

anyone have any answer as to the reason for the error?

**Comment by Nwqda** [comment]
Hi @ManuelQ59, 

You get this error because you are using a free account. That's why Shodan API allows only 5 requests to their server `(limit reached (5))` per free account. If you want to enjoy unlimited requests on Shodan servers you have to pay a subscription.

Little tip: Remove the file `shodan_key.txt`, run de script again and answer `no` to the question: `Do you have a Shodan API key?`.

**Comment by ManuelQ59** [comment]
Ah okey. Thanks for help.
